### PR TITLE
Nitro

### PR DESCRIPTION
**Pull request by Gonhex**
# Name of Resource
Nitro

# Description
All relevant graphics 2D formats

# Which Generation (4/5/Universal)?
Universal

# Notes
Modular documentation of the Nintendo nitro system. The G2D stuff is mostly documented. Other subfamilies just consist of empty files right now to create a directory layout.

### CODE REVIEW

**Comment by BluRosie** [comment]
let me know when you're ready for merge :+1:

**Comment by Gonhex** [comment]
Noted. There is a chance that I will redo the intro texts in general. Have to admit that I was really tired when I wrote them.

**Comment by PlatinumMaster** [comment]
Looks awesome. Definitely fundamental but important documentation. Let us know when it's ready for review!

**Comment by Gonhex** [comment]
It definitely still needs some adjustments but I don't think that I'll continue anytime soon, so I'll reopen it for review. "Allow edits by maintainers" is checked. Feel free to make any changes you deem necessary. Some notes:
- **section_pcmp**: Some people say "CMP" stays for "compression" here. Idk, "count map" made more sense to me but could be wrong.
- **section_char**: The mapping type is very poorly documented right now, I think info from [here (under "DS Video OBJs")](https://problemkaputt.de/gbatek.htm#dsvideoobjs) could fill some gaps.
- **section_cebk**: Probably the most incomplete section here. Also, in the LUT under "Read dimensions", I have no idea how the `{ 1, 2, 3, 4 }` got there. Even the comment says it's supposed to be a copy of the first row. I wrote that code earlier this year for an other project (discontinued!) and either didn't notice it or just don't remember what I was thinking.
- **section_mcbk**: While this document is fully based on my own research, I know that I am not the only one who looked into the format. If you know who else worked on this it might be a good idea to include them in the credits (?)

There is probably more, but that's all I can think of right now.

**Review by PlatinumMaster — APPROVED** [review]

**Pull request merged**
